[workspace]
resolver = "2"
members = [
    "crates/*",
    "crates/duga-tui",
    "crates/duga-runtime",
    "crates/duga-telegram-bot",
    "crates/duga-tools-builtin",
    "crates/duga-mcp",
]

[workspace.package]
edition = "2024"
rust-version = "1.85"

[workspace.dependencies]
pulldown-cmark = { version = "0.13", default-features = false }

[profile.release]
lto = "thin"
codegen-units = 16
strip = true
